"use client";

import { Suspense, useEffect, useState, useRef } from "react";
import { useSearchParams } from "next/navigation";
import { useWhatIfs } from "@/lib/hooks/useWhatIfs";
import SwipeDeck from "@/components/deck/SwipeDeck";
import { Sparkles, Loader2 } from "lucide-react";
import { motion } from "framer-motion";
import { createClient } from "@/lib/supabase/client";
import { getDeckScreen } from "@/lib/utils/deckView";

export default function DeckPage() {
  return (
    <Suspense fallback={<div className="flex min-h-[80vh] items-center justify-center"><Loader2 className="h-8 w-8 animate-spin text-accent-purple" /></div>}>
      <DeckContent />
    </Suspense>
  );
}

function DeckContent() {
  const { cards, loading, generating, generateBatch, swipeCard } = useWhatIfs();
  const searchParams = useSearchParams();
  const [queuedCount, setQueuedCount] = useState(0);
  const [totalCount, setTotalCount] = useState(0);
  const [countsLoaded, setCountsLoaded] = useState(false);
  const [error, setError] = useState("");
  const supabaseRef = useRef(createClient());
  const supabase = supabaseRef.current;
  const autoGenerated = useRef(false);

  // Auto-generate if coming from onboarding
  useEffect(() => {
    if (searchParams.get("generate") === "true" && !autoGenerated.current && !generating) {
      autoGenerated.current = true;
      generateBatch(1).catch((e) => setError(e.message));
    }
  }, [searchParams, generating, generateBatch]);

  // Fetch counts
  useEffect(() => {
    async function getCounts() {
      try {
        const { data: { user } } = await supabase.auth.getUser();
        if (!user) return;

        const { count: queued } = await supabase
          .from("what_ifs")
          .select("*", { count: "exact", head: true })
          .eq("user_id", user.id)
          .eq("status", "queued");

        const { count: total } = await supabase
          .from("what_ifs")
          .select("*", { count: "exact", head: true })
          .eq("user_id", user.id);

        setQueuedCount(queued || 0);
        setTotalCount(total || 0);
      } finally {
        // Mark counts as resolved either way so the deck can tell a brand-new
        // user apart from one whose counts simply haven't loaded yet.
        setCountsLoaded(true);
      }
    }
    getCounts();
  }, [cards, supabase]);

  function handleSwipe(cardId: string, direction: "left" | "right") {
    swipeCard(cardId, direction);
    if (direction === "right") {
      setQueuedCount((c) => c + 1);
    }
  }

  async function handleGenerate() {
    setError("");
    try {
      await generateBatch(Math.ceil(totalCount / 20) + 1);
    } catch (e) {
      setError(e instanceof Error ? e.message : "Generation failed");
    }
  }

  const screen = getDeckScreen({
    loading,
    generating,
    countsLoaded,
    visibleCards: cards.length,
    totalCount,
  });

  if (screen === "loading") {
    return (
      <div className="flex min-h-[80vh] flex-col items-center justify-center">
        <motion.div
          className="text-center"
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
        >
          <Loader2 className="mx-auto h-10 w-10 animate-spin text-accent-purple mb-4" />
          <p className="text-muted">
            {generating ? "Generating your what-ifs... (this takes ~15 seconds)" : "Loading your deck..."}
          </p>
        </motion.div>
      </div>
    );
  }

  if (screen === "first-batch-empty") {
    return (
      <div className="flex min-h-[80vh] flex-col items-center justify-center px-4">
        <Sparkles className="h-12 w-12 text-accent-purple mb-4" />
        <h2 className="font-[family-name:var(--font-playfair)] text-2xl font-bold mb-2">
          No what-ifs yet
        </h2>
        <p className="text-muted mb-6 text-center max-w-sm">
          Hit the button to generate your first batch of opportunities.
        </p>
        {error && <p className="text-red-500 text-sm mb-4 max-w-sm text-center">{error}</p>}
        <button
          onClick={handleGenerate}
          disabled={generating}
          className="rounded-xl gradient-bg px-6 py-3 font-semibold text-white transition hover:opacity-90 disabled:opacity-50"
        >
          Generate 20 What Ifs ✨
        </button>
      </div>
    );
  }

  return (
    <div className="max-w-lg mx-auto">
      <SwipeDeck
        cards={cards}
        onSwipe={handleSwipe}
        totalCount={totalCount}
        queuedCount={queuedCount}
      />

      {error && <p className="text-red-500 text-sm text-center mt-4">{error}</p>}

      {cards.length === 0 && totalCount > 0 && (
        <div className="text-center mt-4">
          <p className="text-muted mb-4">You&apos;ve swiped through all visible cards!</p>
          <button
            onClick={handleGenerate}
            disabled={generating}
            className="rounded-xl gradient-bg px-6 py-3 font-semibold text-white transition hover:opacity-90 disabled:opacity-50"
          >
            Generate 20 More
          </button>
        </div>
      )}
    </div>
  );
}
